{{- if not .Values.onlyApplication }}
{{- $relname := .Release.Name -}}
{{- $numClusters := .Values.clusters -}}
{{- $cluster := .Values.cluster -}}
{{- $flinkVersion := .Values.flinkVersion -}}
{{- range $projectNum, $e := until (int .Values.projects)  }}
{{- range $clusterNum, $e := until (int $numClusters) }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkCluster"
metadata:
  name: music-demo-{{ $clusterNum }}
  labels:
    env: dev-{{ $clusterNum }}
spec:
  imageRef:
    name: 1.9.0
  zookeeperUrl: zookeeper-client:2181

  # Specify Storage Options
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project

  localStorage:
    replicas: 1
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: {{ $cluster.localStorage }}

  # Specify Manager Resources
  jobManager:
    replicas: 1
    memory: 1024M
    cpu: 250m

  taskManager:
    replicas: {{ $cluster.taskManager.replicas }}
    memory: {{ $cluster.taskManager.memory }}
    cpu: {{ $cluster.taskManager.cpu }}
    numberOfTaskSlots: {{ $cluster.taskManager.taskSlots }}
---
{{- end -}}
{{- end -}}
{{- end -}}
