{{- if .Values.flink.applications.switch.musicReader }}
{{- $flinkVersion := .Values.flinkVersion -}}
{{- $application := .Values.application -}}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "music-reader"
spec:
  flinkVersion: {{ $flinkVersion }}
  clusterSelector:
    env: dev-0
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: com.dellemc.desdp.demo.SongPlayReaderJob

  parallelism: {{ $application.defaultParallelism }}

  state: started

  parameters:
    - name: scope
      value: "{{ $application.pravega.pravega_scope }}"

    - name: input-stream
      value: "{{ $application.pravega.pravega_stream }}"

    - name: controller
      value:  "{{ $application.pravega.pravega_controller }}"

{{- end }}
